Update YADM installation script to exclude .fish files from execution

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,24 +1,27 @@
-#!/bin/bash
+#!/bin/sh
 
-# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
-# execute all executable files (excluding templates and editor backups) in the
-# ~/.config/yadm/bootstrap.d directory when run.
+# This script executes all executable files (excluding templates, editor backups, and .fish files)
+# in the ~/.config/yadm/bootstrap.d directory when run.
 
 set -eu
 
-# Directory to look for bootstrap executables in
-BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+# Define the directory to look for bootstrap executables
+bootstrap_dir="${BASH_SOURCE[0]}.d"
 
-if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-    exit 1
+# Check if the bootstrap directory exists
+if [[ ! -d "$bootstrap_dir" ]]; then
+  echo "Error: bootstrap directory '$bootstrap_dir' not found" >&2
+  exit 1
 fi
 
-find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" && ! "$bootstrap" =~ .fish ]]; then
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
-        fi
+# Find and sort all files in the bootstrap directory
+find -L "$bootstrap_dir" -type f | sort | while IFS= read -r file; do
+  # Check if the file is executable and does not match the exclusion patterns
+  if [[ -x "$file" && ! "$file" =~ "##" && ! "$file" =~ "~$" && ! "$file" =~ .fish ]]; then
+    # Try to execute the file, and exit with an error if it fails
+    if ! "$file"; then
+      echo "Error: bootstrap '$file' failed" >&2
+      exit 1
     fi
+  fi
 done
